## 예외 처리

프로그램 실행 시 발생하는 런타임 에러 발생 시, 어떤 동작을 수행해야 하는가에 대한 처리.

프로그램의 비정상 종료를 막고, 정상적인 실행 상태를 유지함.

### try, catch

```java
try {
  // 예외가 실행될만한 코드 
} catch (IOException e) {
  // IOException 이 발생했을 때 실행할 코드
}
```

- catch 블록은 여러 개가 있을 수 있으며, 맨 처음 catch 블록에서 잡히지 않으면 다음 catch 블록에서 검사함.
- 실행할 코드가 한 줄이어도, 괄호({})를 생략할 수 없음.

❗️상속 관계에 있는 예외 중 부모가 위의 catch, 자식이 아래의 catch 로 놓일 수 없다.

**멀티 catch 문**

여러 catch 블럭을 `|`  기호를 통해 하나의 catch 블럭으로 합칠 수 있음. (JDK1.7~)

```java
try {
  ...
} catch (NullPointException | ArrayIndexOutOfBoundsException e) {
  ...
}
```

<br/>

### throw

개발자가 의도적으로 원하는 곳에서 예외를 강제로 발생시킴.

**throw 형태**

```java
throw new 발생시킬_예외();
```

<br/>

### throws

메소드 내에서 예외처리를 하지 않고, **해당 메소드를 사용한 곳에서 예외처리를 하도록** 예외를 상위로 넘김.

메소드 선언부 끝에 작성.

**throws 형태**

```java
메소드명(매개변수1, 매개변수2, ...) throws 예외클래스1, 예외클래스2, ... {}
```

> Exception 만으로 모든 예외를 넘길 수 있음.
>
> ```java
> 메소드명(매개변수2, 매개변수2, ...) throws Exception {}
> ```

throws 키워드가 붙어있는 메소드는 반드시 try 블록 내에서 호출되어야 하며, catch 블록에서 넘겨 받은 예외를 처리해야 한다.

```java
public class Test {
  public static void main(String[] args) {
    int a = 2;
    int b = 0;
    try {
      divide(a, b);
    } catch (ArithmeticException e) {
      e.printStackTrace();
    }
  }
  
  public static int divide (int a, int b) throws ArithmeticException {
    if (b == 0) throw new ArithmeticException("0으로 나눌 수 없습니다.");
    return a / b;
  }
}
```

divide() 에서 예외를 처리하지 않고, throws 키워드를 통해 자신을 호출한 main() 에 전가함.

그래서 divide() 를 호출한 main() 에서 try/catch 문을 통해 예외처리를 진행함.

> **throw 와 throws 의 차이**
>
> throw: 메소드 내에서 예외를 발생시키는 데 사용된다. (예: `throw new FoolException()`)
>
> throws: 해당 메소드가 처리하지 않은 예외를 호출자에게 전달함을 나타낸다. (예: `public void sayNick(String) throws FoolException`)

<br/>

### finally

예외가 발생하거나, 혹은 발생하지 않아도 공통으로 수행되어야 할 코드. 

예외가 발생하지 않는다면, try 블럭 이후에 finally 블럭이 수행됨.

예외가 발생하면 예외 처리를 위한 catch 블럭이 수행된 후 finally 블럭이 수행됨.

```java
Sample sample = new Sample();

try {
  sample.addSample(100);
  sample.printSample(); // 여기서 에러가 발생하면,
  sample.shouldBeRun(); // catch 블럭으로 넘어가 이 함수는 실행되지 않음.
} catch (Exception e) {
  ...
}
```

```java
Sample sample = new Sample();

try {
  sample.addSample(100);
  sample.printSample();
} catch (Exception e) {
  ...
} finally {
  sample.shouldBeRun(); // 에러가 발생해도 반드시 실행됨.
}
```

<br/>

## 예외 계층 구조

<img width="500" src="https://velog.velcdn.com/images%2Fnew_wisdom%2Fpost%2Fb3233d4f-d9e9-4c54-991b-5a0d24430cfb%2Fpngwing.com.png"/>

- 모든 예외의 조상은 Exception 클래스.
- 예외 클래스
  - RuntimeException 클래스와 그 자손 클래스 => Unchecked Exception
  - Exception 클래스와 그 자손 클래스 => Checked Exception

<br/>

## Error vs. Exception

### Error

오류(Error) 는 시스템이 종료되어야 할 수준과 같이 수습할 수 없는 심각한 문제를 의미함.

개발자가 미리 예측하여 방지할 수 없음.

**1. 컴파일 오류**

- 소스코드를 .class 파일로 컴파일하는 과정에서 JVM 이 던지는 오류. 문법적인 오류로 인해 발생하는 경우가 대부분임. 

- `ClassNotFoundException`, `IllegalAccessException`, `NoSuchMethodException` 등.

**2. 런타임 오류**

- 문법적인 오류가 없어 컴파일 시에는 정상적으로 작동하지만, 프로그램을 실행하는 과정에서 발생하는 오류.
- `NullPointerException`, `ArithmeticException`, `IndexOutOfBoundsException` 등.

<br/>

### Exception

예외(Exception) 는 개발자가 구현한 로직에서 발생한 실수나, 사용자의 영향에 의해 발생함.

오류와 달리 개발자가 미리 예측하여 방지할 수 있기 때문에, 상황에 맞는 예외처리(Exception Handle)를 해야 함.

<br/>

## RuntimeException 

**일반 예외 (checked exception)**

자바 소스를 **컴파일하는 과정**에서 예외 처리 코드가 필요한지 검사함.

Exception 을 상속받지만, RuntimeException 은 상속받지 않는다.



**실행 예외 (unchecked exception)**

컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외. RuntimeException 을 상속 받음.

자바 컴파일러가 체크를 하지 않기 때문에, 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다.

**RuntimeException 의 종류**

| 예외                           | 설명                                   |
| ------------------------------ | -------------------------------------- |
| ArithmeticException            | 어떤 수를 0으로 나누는 경우            |
| NullPointerException           | null 객체를 참조하는 경우              |
| ClassCastException             | 적절치 못하게 클래스를 형변환하는 경우 |
| NegativeArraySizeException     | 배열의 크기가 음수값인 경우            |
| OutOfMemoryException           | 사용 가능한 메모리가 없는 경우         |
| NoClassDefFoundException       | 원하는 클래스를 찾지 못한 경우         |
| ArrayIndexOutOfBoundsException | 배열을 참조하는 인덱스가 잘못된 경우   |

<br/>

## Custom Exception

- 일반 예외로 선언할 경우 Exception 을 상속받아 구현.
- 실행 예외로 선언할 경우 RuntimeException 을 상속받아 구현.

- 생성자는 두 개를 선언하는 것이 일반적:
  - 매개 변수가 없는 기본 생성자
  - 예외 발생 원인(예외 메시지)를 전달하기 위해 String 타입의 매개변수를 갖는 생성자

```java
public class CustomException extends RuntimeException{
  
  // 1. 매개 변수가 없는 기본 생성자
  CustomException() {
    
  }
  
  // 2. 예외 발생 원인(예외 메시지)를 전달하기 위해 String 타입의 매개변수를 갖는 생성자
  CustimException(String message) {
    super(message); // RuntimeException 클래스의 생성자를 호출함.
  }
}
```

<br/>

---

**Reference**

[☕ 자바 예외 처리(try catch) 문법 & 응용 정리](https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%ACException-%EB%AC%B8%EB%B2%95-%EC%9D%91%EC%9A%A9-%EC%A0%95%EB%A6%AC)

[Java 예외 처리(Exception) 와 예외 던지기 (throw, throws)](https://day0404.tistory.com/47)

[Java의 Error와 Exception 그리고 예외처리 전략](https://toneyparky.tistory.com/40)

[[Java] 예외의 정의와 종류, 실행 예외(RuntimeException) 알아보기](https://deftkang.tistory.com/44)

[[Java] Exception에 대하여](https://velog.io/@new_wisdom/Exception)

[[Java] 자바 커스텀 예외 만들기(Custom Exception)](https://veneas.tistory.com/entry/Java-커스텀-예외-만들기Custom-Exception)
