## 예외 처리(Exception Handling)하는 이유

>  예외적인 상황을 대비하여 미리 안전장치를 하는 것

서비스가 정상적으로 운영되다가 예외가 발생하면 프로세스가 강제적으로 종료된다.

이러한 예외적인 상황은 예외처리를 통해 프로세스가 강제적으로 종료되지 않고 예외 상황이 발생해도 운영이 가능하도록 핸들링할 수 있다.

<br>
 
## 자바에서 예외 처리 방법
### try-catch

일반적으로 사용하는 예외 처리방법이다.

``` java
try {
	// 예외 발생 가능성이 있는 문장
} catch(예외의 종류){
	// 예외가 발생하면 처리할 문장
}
```

- try 블록
  - 예외 발생 가능성이 있는 문장을 묶는다.
- catch 블록
  - 예외가 발생하면 처리할 문장이다.
  - 매개변수로는 예외의 종류를 넣고, try 블록에서 발생한 예외 메세지나 객체를 인수로 받아 처리한다.
  - catch 블록에 내용을 작성하지 않으면, 어디서 오류가 발생했는지 파악하기가 어렵기 때문에 특수한 경우를 제외하고 로그를 남기는 것이 좋다.


<br>
 
### throw와 throws

📌 **throw**

예외를 발생시키는 키워드다. 

`throw`를 사용하기 위해서는 예외 클래스 객체를 만들어주고 `throw`로 예외를 강제적으로 발생시킨다.

<br>

📌 **throws**

- 예외를 직접 처리하지 않고 '던지는' 것
* JVM에서 생성된 예외 객체를 직접 처리하지 않고 메소드를 호출한 곳으로 넘겨줌 (리턴과 비슷)
* 예외 객체가 반환되면 해당 메소드를 호출한 곳에서는 그 예외 객체를 강제적으로 처리(catch)해줘야 함

> 메소드의 리턴값은 무시해도 되지만 예외 객체는 무시할 수가 없는 것이라 호출한 쪽에서 꼭 처리를 해줘야 한다.

예외가 여러개라면 쉼표(,)로 구분한다.

```java
void method() throws Exception1, Exception2, ... {... }
```

`throws`는 예외를 떠넘기는 것 뿐, 예외를 처리하는 것이 아니다.

> 💡**참고**<br>
> `throws`로 예외를 선언하면 자식 타입의 예외까지도 발생할 수 있다.<br>
> 오버라이딩할 때는 단순히 선언된 예외의 개수가 아니라 상속관계까지 고려해야 한다.<br><br>
> 
> 예시<br>
> `IllegalMonitorStateException` 은 `RuntimeException` 클래스의 자식이기 때문에 `IllegalMonitorStateException`은 예외 처리를 하지않아도 된다.<br>
> Java API 문서를 보고 메소드의 선언부와 thorws 부분을 보고 메소드끼리 연관 지어서 확인해주는 것이 좋다.


``` java
public class Main {
	public static void main(String[] args) throws Exception {
		method1(); 
	}
	static void method1() throws Exception{
		method2();
	}
	static void method2() throws Exception{
		throw new Exception();
	}
}
```

<br>
 
### finally

예외 발생 여부와 관계없이 **무조건 실행되어야하는 문장**이다.

**try-catch**문의 끝에 선택적으로 덧붙여 사용할 수 있으며 **try-catch-finally**의 순서로 구성된다.

``` java
try {
	//예외 발생가능성 문장
}catch (Exception1 e1) {
	//예외발생시 예외처리 문장
}finally {
	//항상 수행되어야 하는 문장
}
```


<br>


### try-finally 와 try-with-resources

자바 7부터 제공하는 **try-with-resources**는 자원을 닫아주는 역할을 한다.

try-with-resources 를 사용하면 `close()`를 호출하지 않다고 예외가 발생한 여부와 관계없이 `finally`와 같이 반드시 `close()` 메소드가 호출된다.

> 자원 닫기는 예측할 수 없는 성능 문제로 이어지기도 하기 때문에 사용이 종료되었으면 반드시 닫아줘야한다.

자원을 회수할 때 try-finally 블럭을 이용해서 사용한 자원을 회수할 수 있는데, `finally`는 해당 절 내에서도 `예외가 발생하는 경우가 있다. 

또한 try-finally 블럭을 사용해 자원을 회수하면 코드가 복잡해지는 경우가 많아 try-with-resource 를 사용하여 코드를 더 짧고, 분명해지도록 구현이 가능하다.

**try-finally**
 
``` java
public class ExceptionTest {
    public static void main(String[] args) {
        FileInputStream file = null;
        try {
            file = new FileInputStream("Lemonade");
        } catch (FileNotFoundException e) {
            System.out.println("파일이 존재하지 않습니다. : " + e.getMessage());
        } catch (Exception e) {
            System.out.println("파일이 존재하지 않습니다 : " + e.getMessage());
        } finally {
            if (file != null) {
                try {
                    file.close(); // 파일 입력 스트림 close
                } catch (IOException e) {
                    System.out.println("" + e.getMessage());
                }
            }
        }
    }
}

```

**try-with-resource**

``` java
public class ExceptionTest {
    public static void main(String[] args) {
        try(FileInputStream file = new FileInputStream("Lemonade")) {
            
        } catch(FileNotFoundException e) {
            System.out.println("파일이 존재하지 않습니다. : " + e.getMessage());
        } catch(IOException e) {
            e.printStackTrace();
        } catch(Exception e) {
            System.out.println("파일이 존재하지 않습니다 : " + e.getMessage());
        }
    }
}
```


<br>
 
## 자바가 제공하는 예외 계층 구조

모든 예외의 조상은 `java.lang.Throwable` 클래스다.

자바에서의 예외 계층 구조는 다음과 같다.

모든 클래스의 최상위 클래스인 `Object` 클래스를 확장한 모든 예외의 조상 클래스인 `Throwable` 클래스, 그리고 `Throwable` 클래스를 확장한 `Error` 클래스와 `Exception` 클래스로 분류할 수 있다.
- Error 클래스: 자바 프로그램 외에서 발생하는 오류 
- Exception 클래스: 자바 프로그램 내에서 발생하는 오류

![예외계층구조](https://github.com/NewSainTurtle/CS-study/assets/26339069/6c0a45fd-9915-4f4f-a85d-7b7cb731b3d1)


<br>
 
## Exception과 Error의 차이

프로그램 실행 중에 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우가 있는데, 이런 경우의 원인을 **에러 또는 오류**라고 한다.

에러는 발생 시점에 따라 3가지로 구분한다.
- **컴파일 에러**: 컴파일 시 발생하는 에러 
  - `.class` 파일을 컴파일하는 과정에서 JVM이 던지는 오류
- **런타임 에러**: 실행 시 발생하는 에러
- **논리적 에러**: 실행은 되는데 의도와 다르게 동작하는 에러


자바 프로그래밍에서는 실행 시 발생할 수 있는 오류를 에러와 예외로 구분한다.
- **에러(error)**: 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- **예외(exception)**: 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

에러는 메모리 부족 `OutOfMemoryError`나 스택오버플로우 `StackOverflowError`와 같이 일단 발생하면 복구할 수 없는 심각한 오류이며, 예측이 불가능하다. 

**즉, 에러는 JVM 실행에 문제가 생긴 것이므로 개발자가 대처할 방법이 없다.**

반면 예외는 발생하더라도 수습될 수 있는 비교적 덜 심각한 오류를 말한다.

대부분의 예외는 개발자가 구현한 로직에서 발생한 실수나 사용자의 영향에 의해 발생한다.

그래서 **예외는 에러와 달리 문제가 발생하더라도 이에 대한 대응 코드를 미리 작성해 놓음으로써 어느 정도 프로그램의 비정상적인 종료 혹은 동작을 막을 수 있다.(= 예외처리)**

자바에서 다루는 모든 예외 오류는 `Exception` 클래스에서 처리한다.

Exception 클래스는 두가지로 분류할 수 있다.
- RuntimeException 클래스
- RE를 제외한 Exception 클래스 및 하위 클래스

> 예외처리의 정의는 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것이고,<br>
> 예외처리의 목적은 프로그램의 비정상적인 종료를 막고 정상적인 실행상태를 유지하는 것이다.



<br>
 
## RuntimeException과 RE가 아닌 것의 차이

`RuntimeException`은 `unchecked exception`이라고도 한다.

`checked exception`은 `RuntimeException`를 제외한 나머지로, Exception 클래스 및 하위 클래스이다. 

- **unchecked exception (RuntimeException)**
  - 예외는 선택: 예외 처리를 강제적으로 하지 않는다.
  - 프로그래머의 실수로 발생하는 예외
    - 배열의 범위를 벗어남 (`IndexOutOfBoundsException`)
    - 값이 null인 참조 변수의 멤버를 호출 (`NullPointerException`)
    - 클래스 간의 형 변환을 잘못함 (`ClassCastException`)
    - 정수를 0으로 나누는 산술 오류 (`ArithmeticException`)
    - …
- **checked exception**
  - 예외를 반드시 처리: 예외처리를 하지 않으면, 컴파일이 되지 않는다.
  - 사용자의 실수와 같은 외적인 요인에 의해 발생하는, 컴파일 시 발생하는 예외
    - 존재하지 않는 파일의 이름을 입력 (`FileNotFoundException`)
    - 실수로 클래스의 이름을 잘못 기재 (`ClassNotFoundException`)
    - 입력한 데이터 형식이 잘못된 경우 (`DataFormatException`)
    - …


```java
public static void main(String[] args) {
	// checked exception
	try {
		throw new Exception();
	} catch(Exception e) {
	System.out.println("checked exception은 반드시 예외 처리가 필요합니다.");
	}

	// unchecked exception
	throw new RuntimeException("unchecked exception은 예외 처리가 선택적입니다.");
}
```

<br>
 
## 커스텀한 예외 만드는 방법

기존의 정의된 예외 클래스 외에 사용자가 직접 커스텀해서 예외를 만들어 처리하는 것이 가능하다.

일반적으로 `Exception` 클래스를 상속받아 사용하며, 필요에 따라 맞는 예외 클래스를 선택해 사용한다.

``` java
public class Main {
	public static void main(String[] args) {
		try {
			startInstall();
			copyFiles();
		}catch(SpaceException e) {
			System.out.println("에러 :"+ e.getMessage());
			e.PrintStackTrace();
		}
	}
}

class SpaceException extends Exception{
	SpaceException(String msg){ //문자열을 매개변수로 받는 생성자
		super(msg); //부모인 Exception클래스의 생성자를 호출한다.
	}
}
```

<br>
 
> 참고 <br>
> [1] [https://velog.io/@pearl0725](https://velog.io/@pearl0725/%EC%9E%90%EB%B0%94%EC%97%90%EC%84%9C-%EC%98%88%EC%99%B8%EB%A5%BC-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)<br>
> [2] https://resilient-923.tistory.com/117 <br>
> [3] https://codevang.tistory.com/143 <br>
> [4] [https://inpa.tistory.com](https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EC%97%90%EB%9F%ACError-%EC%99%80-%EC%98%88%EC%99%B8-%ED%81%B4%EB%9E%98%EC%8A%A4Exception-%F0%9F%92%AF-%EC%B4%9D%EC%A0%95%EB%A6%AC#%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%9D%98_%EC%98%A4%EB%A5%98_%EC%A2%85%EB%A5%98)


<br>
 
